config/routes.rb
Chriskinoti::Application.routes.draw do
   
  match '/manifesto', to: 'manifesto#index'

  match '/learn' ,to: 'posts#show'
	
	
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  
  match '/gallery' ,to:  'gallery#works'

  match '/contacts' ,to:  'pages#contacts'
  
  root to: "pages#home"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/art.rb
class Art < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/sandbox.rb
class Sandbox < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def works
  	
  	
  	
  end
end

app/controllers/manifesto_controller.rb
class ManifestoController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end

  def contacts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	

end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/manifesto_helper.rb
module ManifestoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sandbox_helper.rb
module SandboxHelper
end

app/views/gallery/works.html.erb
<div class="wrapper thumbs_wrapper">
<div class="thumbs">
			<%= image_tag("thumbs/1.jpg")%>
			<%= image_tag("thumbs/2.jpg")%>
			<%= image_tag("thumbs/3.jpg")%>
			<%= image_tag("thumbs/4.jpg")%>
			<%= image_tag("thumbs/1.jpg")%>
			<%= image_tag("thumbs/2.jpg")%>
			<%= image_tag("thumbs/3.jpg")%>
			<%= image_tag("thumbs/4.jpg")%>
			<%= image_tag("thumbs/1.jpg")%>
			<%= image_tag("thumbs/2.jpg")%>
			<%= image_tag("thumbs/3.jpg")%>
			<%= image_tag("thumbs/4.jpg")%>
			<%= image_tag("thumbs/1.jpg")%>
			<%= image_tag("thumbs/2.jpg")%>
			<%= image_tag("thumbs/3.jpg")%>
			<%= image_tag("thumbs/4.jpg")%>

</div>
</div>

<%= render 'pages/footer'%>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
  	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chris kinoti</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
<%= render 'layouts/shim' %>

</head>

<body>

<%= yield %>

</body>

</html>

app/views/manifesto/index.html.erb
<div class="container">
        	
			<div class="sp-slideshow">
			
				<input id="button-1" type="radio" name="radio-set" class="sp-selector-1" checked="checked" />
				<label for="button-1" class="button-label-1"></label>
				
				<input id="button-2" type="radio" name="radio-set" class="sp-selector-2" />
				<label for="button-2" class="button-label-2"></label>
				
				<input id="button-3" type="radio" name="radio-set" class="sp-selector-3" />
				<label for="button-3" class="button-label-3"></label>
				
				<input id="button-4" type="radio" name="radio-set" class="sp-selector-4" />
				<label for="button-4" class="button-label-4"></label>
				
				<input id="button-5" type="radio" name="radio-set" class="sp-selector-5" />
				<label for="button-5" class="button-label-5"></label>
				
				<label for="button-1" class="sp-arrow sp-a1"></label>
				<label for="button-2" class="sp-arrow sp-a2"></label>
				<label for="button-3" class="sp-arrow sp-a3"></label>
				<label for="button-4" class="sp-arrow sp-a4"></label>
				<label for="button-5" class="sp-arrow sp-a5"></label>
				
				<div class="sp-content">
					<div class="sp-parallax-bg"></div>
					<ul class="sp-slider clearfix">
						<li><%= image_tag("image1.png", alt: "image01")%></li>
						<li><%= image_tag("image2.png", alt: "image02") %></li>
						<li><%= image_tag("image3.png", alt: "image03")%></li>
						<li><%= image_tag("image4.png", alt: "image04")%></li>
						<li><%= image_tag("image5.png", alt: "image05")%></li>
					</ul>
				</div><!-- sp-content -->
				
			</div><!-- sp-slideshow -->
			</div>
<%= render 'pages/footer'%>

				
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			


	
	

app/views/pages/_footer.html.erb
<footer>
	<div id="footer">
		<div class="legal">
	    <p>&copy; 2012-now all rights reserved chris kinoti arts</p>
	    </div>
	    
	</div>
</footer>

app/views/pages/contacts.html.erb
<section>
	<div class="contact_details">
		<div id="name">
			<p>chris kinoti</p>
			<p>hacker & painter</p>
			
		</div>
	
	
		<ul>
			<li>facebook</li>
			<li>twitter</li>
			<li>tumblr</li>
			<li>google+</li>
		</ul>
	</div>
</section>
	

app/views/pages/home.html.erb
<%= image_tag("moreno.jpg",alt: "2",id: 'background' )%>
<div id="maincontent">
	
<div class="home_container">
	<ul class="ch-grid">
		<li>
			<div class="ch-item ch-img-1">
				<div class="ch-info-wrap">
					<div class="ch-info">
						<div class="ch-info-front ch-img-1"></div>
						<div class="ch-info-back">
							<h3>contacts</h3>
							<p><%= link_to "contacts" , contacts_path %></p>
						</div>
					</div>
				</div>
			</div>
		</li>
		
		<li>
			<div class="ch-item ch-img-2">
				<div class="ch-info-wrap">
					<div class="ch-info">
						<div class="ch-info-front ch-img-2"></div>
						<div class="ch-info-back">
							<h3>gallery</h3>
							<p><%= link_to "gallery" , gallery_path %></p>
						</div>
					</div>
				</div>
			</div>
		</li>
		
		<li>
			<div class="ch-item ch-img-3">
				<div class="ch-info-wrap">
					<div class="ch-info">
						<div class="ch-info-front ch-img-3"></div>
						<div class="ch-info-back">
							<h3>manifesto</h3>
							<p><%= link_to "manifesto" , manifesto_path %></p>
						</div>
					</div>
				</div>
			</div>
		</li>
	</ul>
	</div>	
	
	</div>
	
<script type="text/javascript">
$(window).load(function() {
	$("#background").fullBg();
});
</script>
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
<%= render 'pages/footer'%>

app/views/posts/new.html.erb
<h1> blog design </h1>